name: Tool definition file validation and tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  lint-tool-definition-files:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: install planemo
        run: pip install planemo
      
      - name: lint compareSTR
        run: planemo lint CompareSTR/compareSTR.xml

      - name: lint dumpSTR
        run: planemo lint DumpSTR/dumpSTR.xml
      
      - name: lint qcSTR
        run: planemo lint qcSTR/qcSTR.xml
      
      - name: lint statSTR
        run: planemo lint StatSTR/statSTR.xml



      
