name: Tool definition file validation and tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  lint-tool-definition-files:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: install planemo
        run: pip install planemo
      
      - name: lint compareSTR
        run: planemo lint CompareSTR/compareSTR.xml

      - name: lint dumpSTR
        run: planemo lint DumpSTR/dumpSTR.xml
      
      - name: lint qcSTR
        run: planemo lint qcSTR/qcSTR.xml
      
      - name: lint statSTR
        run: planemo lint StatSTR/statSTR.xml

      - name: lint mergeSTR
        run: planemo lint MergeSTR/mergeSTR.xml
    
  test-tool-definition-files:
    runs-on: ubuntu-latest
    needs: lint-tool-definition-files
    steps:
      - uses: actions/checkout@v2

      - name: install planemo
        run: pip install planemo
      
      - name: install galaxy
        run: git clone -b release_22.01 https://github.com/galaxyproject/galaxy.git
      
      - name: test compareSTR
        run: planemo test --galaxy_root=galaxy CompareSTR/compareSTR.xml

      - name: test dumpSTR
        run: planemo test --galaxy_root=galaxy DumpSTR/dumpSTR.xml
      
      - name: test qcSTR
        run: planemo test --galaxy_root=galaxy qcSTR/qcSTR.xml
      
      - name: test statSTR
        run: planemo test --galaxy_root=galaxy StatSTR/statSTR.xml
      
      - name: test mergeSTR
        run: planemo test --galaxy_root=galaxy MergeSTR/mergeSTR.xml




      
