# This is a basic workflow to help you get started with Actions

name: Tool definition file validation and tests

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  lint-compareSTR:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: install planemo
        run: pip install planemo
      
      - name: lint compareSTR
        run: planemo lint CompareSTR/compareSTR.xml

      - name: lint dumpSTR
        run: planemo lint DumpSTR/dumpSTR.xml
      
      - name: lint qcSTR
        run: planemo lint qcSTR/qcSTR.xml
      
      - name: lint statSTR
        run: planemo lint StatSTR/statSTR.xml



      
